Create CustomInput
waleedtarbosh/Instagram-Clone pull request #4
Opened 2023-05-10 11:38 UTC by waleedtarbosh

2023-05-10 15:26 UTC, iamhaitham requested changes

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
The file name is **l**ogin.js. 
It should be **L**ogin.js

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
> +  return (
Make sure to correct the indentation and have it formatted correctly

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
> +export default function Login() {
Please have a break line between the component and the imports

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
> +
I think you will write the try part in a later PR, so I will leave it.
Also, the function is async although you are not awaiting anything. But I suppose it's for the same reason.

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
> +  return (
Have a break line before the return

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/login.js
> +            />
One CustomInput is enough.
Use an array to display different data.

2023-05-10 15:26 UTC, iamhaitham commented on src/pages/Login/CustomInput/CustomInput.js
> +const CustomInput = ({ ariaLabel, type, placeholder, styleInput, onChange, value }) => {
Instead of having a long line of props, please have each one of them in a separate line.
Make sure to maintain the indentation when you do that.

2023-05-11 20:50 UTC, waleedtarbosh commented on src/pages/Login/login.js
> +
This is absolutely true. I did it to use Firebase later.

2023-05-12 08:00 UTC, iamhaitham commented on src/pages/Login/login.js
@waleedtarbosh I am talking about the file's name. 
The first letter of a react component should start with a capital letter, right?

2023-05-12 08:01 UTC, iamhaitham approved these changes

2023-05-12 08:33 UTC, waleedtarbosh commented on src/pages/Login/login.js
done.

2023-05-12 17:05 UTC, merged