Create Paragraph Component
waleedtarbosh/Instagram-Clone pull request #6
Opened 2023-05-10 11:50 UTC by waleedtarbosh

2023-05-10 15:50 UTC, iamhaitham requested changes

2023-05-10 15:50 UTC, iamhaitham commented on src/pages/Login/login.js
> +  };
Again, either have all the props for all the components stored in dedicated constants, or just pass it in-line. 
The code will look more organized if you follow one approach.

2023-05-10 15:50 UTC, iamhaitham commented on src/pages/Login/login.js
> +      navigate(ROUTES.DASHBOARD);
Could you please leave this part until you do the validations on the backend? 
Because I don't find it logical to always navigate me to the dashboard.

2023-05-10 15:50 UTC, iamhaitham commented on src/pages/Login/Paragraph/Paragraph.js
> +      {textParagraph }{' '}
Create a constant and assign it the concatenation of both strings, then just display that constant in the JSX.
Please don't use (string + string), and instead use the string literal approach.

2023-05-10 15:50 UTC, iamhaitham commented on src/pages/Login/Paragraph/Paragraph.js
> +const Paragraph = ({ textParagraph , textLink, styleParagraph , signUpLinkProps }) => {
1. textParagraph and styleParagrah are not good names. For example if in the login.js file, I know I am calling the Paragraph component, so why will I use its name in its props as well? 
2. Anyone who reads signUpLinkProps will think that this component is only used for the signups, and they will not use your component, which breaks its reusability. Give this prop a better, more general name.

2023-05-11 22:18 UTC, waleedtarbosh commented on src/pages/Login/Paragraph/Paragraph.js
> +      {textParagraph }{' '}
done.

2023-05-11 22:35 UTC, waleedtarbosh commented on src/pages/Login/Paragraph/Paragraph.js
> +const Paragraph = ({ textParagraph , textLink, styleParagraph , signUpLinkProps }) => {
done.

2023-05-12 08:26 UTC, iamhaitham commented on src/pages/Login/Paragraph/Paragraph.js
> +      {textParagraph }{' '}
const concatenatedText = `${text}  `;

2023-05-12 08:27 UTC, iamhaitham requested changes
No all comments are fixed yet.
@waleedtarbosh

2023-05-12 14:23 UTC, iamhaitham approved these changes
As we have discussed it offline, let's open a dedicated PR for [this comment](https://github.com/waleedtarbosh/Instagram-Clone/pull/6#discussion_r1190099395), and I will approve this PR as discussed.

2023-05-12 17:25 UTC, merged